Ability to set URL limit for specific domain
crawler-commons/url-frontier pull request #91
Opened 2024-07-31 20:45 UTC by zaibacu

Implementation of Feature request: https://github.com/crawler-commons/url-frontier/issues/90

2024-08-01 07:17 UTC, jnioche requested changes
Minor change required but looks good otherwise. Thanks!

2024-08-01 07:17 UTC, jnioche commented on service/src/main/java/crawlercommons/urlfrontier/service/QueueInterface.java
> +    public Boolean IsLimitReached();
minor nitpick -> `isLimitReached` (lowercase initial i)

2024-08-01 07:43 UTC, zaibacu commented on service/src/main/java/crawlercommons/urlfrontier/service/QueueInterface.java
> +    public Boolean IsLimitReached();
Yeah, sorry, too much Golang lately :)

2024-08-02 08:06 UTC, merged

2024-08-02 08:06 UTC, jnioche commented
thanks @zaibacu